name: docker-stack-deploy
services:
  deployer:
    image: ghcr.io/wez/docker-stack-deploy
    container_name: docker-stack-deploy
    restart: always
    # we need the hostname of the host to correctly match runs_on rules
    uts: host
    environment:
      # required: the git repo url to clone, username and password
      - GITHUB_URL=${GITHUB_URL}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # required: passphrase to unlock secrets database in your repo
      - STACK_KDBX_PASS=${STACK_KDBX_PASS}
      # optional: how many seconds between git pulls
      - POLL_INTERVAL=${POLL_INTERVAL}
      - STACK_REPO_DIR=/var/lib/docker-stack-deploy/repo
    volumes:
      # required to enable spawning containers on the host
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker-stack-deploy:/var/lib/docker-stack-deploy
