name: Build Image

on:
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "Cargo.toml"
      - ".github/workflows/build-image.yml"
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/wez/docker-stack-deploy:latest
          push: ${{ github.event_name != 'pull_request' }}
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max


